use_frameworks!

project 'native-navigation.xcodeproj'

target 'native-navigation_Example' do
  pod 'native-navigation', :path => '../../'
  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork'
    # Add any other subspecs you want to use in your project
  ]
end
