react_native_path = '../../node_modules/react-native'

use_frameworks!

project 'native-navigation.xcodeproj'

target 'native-navigation' do
  pod 'native-navigation', :path => '../../'

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga/yoga.podspec'

  # Third party deps used for CxxBridge
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'DevSupport',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork'
    # Add any other subspecs you want to use in your project
  ]
end
